### ISSUE TITLE
AssignmentML4.ipynb not compatible with Python 3.9 which is the only one available on Watson

### ISSUE THREAD

**Issue by Hasnael07** [IBM/claimed#195]
@romeokienzler week 4 assignment of the Advanced machine learning and signal processing course on Coursera needs some updates. Many students and I are stuck on it and can't validate the course because of it. It seems that the provided systemml version is not compatible with Python 3.9, but works only until Python 3.8, which for some reason can't be selected in Watson studio as it always says "Notebook environments with Python 3.8 are restricted to notebooks that are already using them. Choose an environment with Python 3.9 instead."
Here are the available versions (the notebook doesn't work with the option Default Python 3.8 + Watson NLP (beta)):
![image](https://user-images.githubusercontent.com/97097212/165720736-3e632a0b-991a-48c0-8ab1-c1e1c3d08f93.png)
The error occurs in cell 6 when calling MLContext(spark). This is the error: TypeError: 'JavaPackage' object is not callable

Thank you.

**Comment by GhostOfGreg** [comment]
@romeokienzler same problem here, please update the assignment, so it runs on the new Watson Studio environment without giving errors just because of out-dated libraries / environments / packages. Thank you!

**Comment by romeokienzler** [comment]
Someone is assigned to take care of it...

**Comment by romeokienzler** [comment]
@GhostOfGreg can u pse try again by re-importing the latest version? should be fixed now..
