### ISSUE TITLE
link rot in assignment 2.1

### ISSUE THREAD

**Issue by jamesnordlund** [IBM/claimed#201]
Notebook: https://github.com/IBM/coursera/blob/master/coursera_ds/assignment2.1_spark2.3_python3.6.ipynb

The link: https://spark.apache.org/docs/latest/api/python/pyspark.sql.html#pyspark.sql.DataFrame is dead.

Possibly the intent is to point to here: https://spark.apache.org/docs/latest/api/python/reference/pyspark.sql/dataframe.html.

**Comment by romeokienzler** [comment]
Thanks so much @jamesnordlund - fixed in bd563759b4cded81e01afca449791460fad98c6c
